SUCCESS_RESPONSE_CODE = "200" # This is the SUCCESS RESPONSE CODE TO THE RESPONSE CODE
UNSUCCESS_RESPONSE_CODE = "400" #This is the UNSUCCESS RESPONSE CODE TO THE RESPONSE CODE

RESPONSE_CODE_KEY = "responseCode" #THIS IS THE MESSAGE KEY OF ANY BOTH SUCCESS RESPONSE CODE OR UNSUCCESS RESPONSE CODE TO BE INCLUDED IN THE JSON

RESPONSE_MESSAGE_KEY = "message" #THIS IS THE MESSAGE KEY OF ANY MESSAGES TO BE INCLUDED IN THE JSON

RESULT_DATA = "data" #KEY FOR THE ANY DATA TO BE SEND IN JSON
ERROR_KEY = "errors" #KEY FOR THE ERROR OCCURED IN THE JSON