# Generated by Django 5.0.3 on 2024-06-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_created_by_patient_created_date'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.userinfo'),
        ),
    ]
