# Generated by Django 5.0.6 on 2024-06-05 10:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_clinician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=100)),
                ('assessment_date', models.DateField()),
                ('questions_and_answers', ckeditor.fields.RichTextField()),
                ('final_score', models.FloatField()),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
        ),
    ]
