# Generated by Django 5.0.3 on 2024-06-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions_and_answers',
            field=models.TextField(),
        ),
    ]
